default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: melon4040
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: Nick_Nack_Note_development

test:
  <<: *default
  database: Nick_Nack_Note_test

production:
  <<: *default
  database: Nick_Nack_Note_production
  username: nick_nack_no
  password: <%= ENV['NICK_NACK_NOTE_DATABASE_PASSWORD'] %>
